// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsX6uB4ZY47_kqAFmPIphe-vEnSDtM77c',
    appId: '1:35110575993:web:32306385ff832105bed9a8',
    messagingSenderId: '35110575993',
    projectId: 'patryk-sewastianowicz',
    authDomain: 'patryk-sewastianowicz.firebaseapp.com',
    storageBucket: 'patryk-sewastianowicz.appspot.com',
    measurementId: 'G-9WEQPRMBLT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6gpyCnNFxV53R8G2L3IrKyLj0JUkwQWc',
    appId: '1:35110575993:android:c7bcf8e97158c86cbed9a8',
    messagingSenderId: '35110575993',
    projectId: 'patryk-sewastianowicz',
    storageBucket: 'patryk-sewastianowicz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzsCJ3HsX5emXjdCa2bFQtumD9A7mU30k',
    appId: '1:35110575993:ios:53fd9b3668df277fbed9a8',
    messagingSenderId: '35110575993',
    projectId: 'patryk-sewastianowicz',
    storageBucket: 'patryk-sewastianowicz.appspot.com',
    iosClientId: '35110575993-c3agnsk7eqgk77kmfec825v87gp8irtc.apps.googleusercontent.com',
    iosBundleId: 'com.example.cv',
  );
}
