// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhwMKJm-aKxGRMYXVAjkFu-esLkMbJmlM',
    appId: '1:564519777040:web:f934535401015d7ab82b95',
    messagingSenderId: '564519777040',
    projectId: 'resume-14121',
    authDomain: 'resume-14121.firebaseapp.com',
    storageBucket: 'resume-14121.appspot.com',
    measurementId: 'G-0WEN5245DN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtIbgJdrAJkEzQJXDXeycdFidj8gnY66U',
    appId: '1:564519777040:android:831d7acc63d497aab82b95',
    messagingSenderId: '564519777040',
    projectId: 'resume-14121',
    storageBucket: 'resume-14121.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCreUuzJGw-JHuKd917IIIbpjiQMB9yvMY',
    appId: '1:564519777040:ios:5e9a9baa17983c9cb82b95',
    messagingSenderId: '564519777040',
    projectId: 'resume-14121',
    storageBucket: 'resume-14121.appspot.com',
    iosClientId: '564519777040-fhqba9mg2t707g5jlql2arua8qe76od5.apps.googleusercontent.com',
    iosBundleId: 'com.example.cv',
  );
}
